spring:
  application:
    name: fraud-detection-service
  data:
    redis:
      host: localhost
      port: 6379
  kafka:
    bootstrap-servers: localhost:9092

    consumer:
      group-id: account-service-group
      auto-offset-reset: earliest

      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer

      properties:
        spring.json.trusted.packages: "*"
        spring.json.use.type.headers: false
        spring.json.value.default.type: java.util.HashMap

    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer


server:
  port: 8084

  # account service URL for feign Client

account:
  service:
    url: http://localhost:8081

fraud:
  max-transaction-per-minute: 5
  suspicious-amount-multiplier: 5
  max-balance-percentage: 0.90

management:
  endpoints:
    web:
      exposure:
        include: health, info

